package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import greendao.TBase;

import greendao.TBaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tBaseDaoConfig;

    private final TBaseDao tBaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tBaseDaoConfig = daoConfigMap.get(TBaseDao.class).clone();
        tBaseDaoConfig.initIdentityScope(type);

        tBaseDao = new TBaseDao(tBaseDaoConfig, this);

        registerDao(TBase.class, tBaseDao);
    }
    
    public void clear() {
        tBaseDaoConfig.clearIdentityScope();
    }

    public TBaseDao getTBaseDao() {
        return tBaseDao;
    }

}
